### ISSUE TITLE
infinigag unofficial api is down

### ISSUE THREAD

**Issue by plowsec** [cinatic/gnome-shell-extension-neingag#3]
neingag extension is not working anymore and it appears to be caused by the unofficial api it uses, which seems to be no longer maintained.

some alternatives to infinigag : 
https://github.com/and3rson/nineapi
https://www.npmjs.com/package/node-9gag

**Comment by cinatic** [comment]
yes unfortunately it stopped working a long time ago

first one is a crawler which means lot of traffic (vs. json api) i will check if the requests have reasonable size the other one looks more promissing.

thanks

**Comment by plowsec** [comment]
either way, let me know if you need help, I would be happy to contribute.

**Comment by cinatic** [comment]
that would be great, could you please check if this approach is still working and how the response look like:

https://github.com/and3rson/nineapi

**Comment by plowsec** [comment]
Yes it still works, but you need to use valid credentials.
 Examples of responses with a dummy account here (I still hid pass and mail for obvious reasons) :
[responses.txt](https://github.com/cinatic/gnome-shell-extension-neingag/files/977416/responses.txt)

**Comment by cinatic** [comment]
nice ty! Imho the android app can also fetch posts w/o login, anyway if this doesn't work we can add settings for credentials. 

Ccan you write a service class which replaces gagServices.js. I will prepare the settings and do some tests with the api

**Comment by cinatic** [comment]
added another source and commited code to extension.gnome.org but it needs to be approved
